#service: my-service
#runtime: java
#env: flexible
#runtime_config:
  #jdk: openjdk8
#env_variables:
  #SPRING_PROFILES_ACTIVE: "gcp"
#handlers:
#- url: /.*
 # script: this field is required, but ignored
#beta_settings:
  #cloud_sql_instances: amar-gae-project-342615:us-east1:amar-gae-postgresql=tcp:5432

service: my-service
env: flex
runtime: java
runtime_config:
  jdk: openjdk8

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5

handlers:
  - url: /.*
    script: this field is required, but ignored